CREATE TABLE IF NOT EXISTS "endpoint_hits"
(
    "hit_id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "app"    VARCHAR   NOT NULL,
    "uri"    VARCHAR   NOT NULL,
    "ip"     VARCHAR   NOT NULL,
    "time"   TIMESTAMP NOT NULL,
    CONSTRAINT pk_endpoint_hit PRIMARY KEY ("hit_id"),
    CONSTRAINT view_not_in_future CHECK ("time" <= CURRENT_TIMESTAMP)
);